spring.application.name=hexagonal
spring.datasource.url=jdbc:sqlite:hexagonal.db
spring.datasource.driverClassName=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update